blueprint:
    name: IKEA Rodret Use with Zigbee2MQTT
    description: Control Light Entity(ies)
    domain: automation
    author: Beckynet
    input:
      rodret_entity:
        name: Rodret remote
        description: IKEA Rodret remote
        selector:
          entity:
            filter:
              - integration: mqtt
              - domain:
                - sensor
      target_lights:
        name: Target Lights
        description: Select multiple lights
        selector:
          entity:
            filter:
              - domain: light
            multiple: true

source_url: https://github.com/beckynet/HA_Blueprints/blob/main/IKEA_Rodret/ikea_rodret.yaml

variables:
  light_entities: !input target_lights

trigger:
  - platform: state
    entity_id: !input rodret_entity

condition: []

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'on' }}"
        sequence:
          - action: light.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: !input target_lights
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'off' }}"
        sequence:
          - action: light.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: !input target_lights
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'brightness_move_up' }}"
        sequence:
          - variables:
              total_brightness: >
                {% set ns = namespace(total = 0) %}
                {% for light in light_entities %}
                  {% if state_attr(light, 'brightness') is not none %}
                    {% set ns.total = ns.total + state_attr(light, 'brightness') %}
                  {% endif %}
                {% endfor %}
                {{ ns.total }}
              light_count: >
                {% set ns = namespace(count = 0) %}
                {% for light in light_entities %}
                  {% if state_attr(light, 'brightness') is not none %}
                    {% set ns.count = ns.count + 1 %}
                  {% endif %}
                {% endfor %}
                {{ ns.count }}
              average_brightness: >
                {% if light_count > 0 %}
                  {{ (total_brightness / light_count) | int }}
                {% else %}
                  0
                {% endif %}
          - action: light.turn_on
            metadata: {}
            target:
              entity_id: !input target_lights
            data:
              brightness: >
                {% set new_brightness = average_brightness + 25 %}
                {% if new_brightness > 255 %}
                  255
                {% else %}
                  {{ new_brightness }}
                {% endif %}
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'brightness_move_down' }}"
        sequence:
          - variables:
              total_brightness: >
                {% set ns = namespace(total = 0) %}
                {% for light in light_entities %}
                  {% if state_attr(light, 'brightness') is not none %}
                    {% set ns.total = ns.total + state_attr(light, 'brightness') %}
                  {% endif %}
                {% endfor %}
                {{ ns.total }}
              light_count: >
                {% set ns = namespace(count = 0) %}
                {% for light in light_entities %}
                  {% if state_attr(light, 'brightness') is not none %}
                    {% set ns.count = ns.count + 1 %}
                  {% endif %}
                {% endfor %}
                {{ ns.count }}
              average_brightness: >
                {% if light_count > 0 %}
                  {{ (total_brightness / light_count) | int }}
                {% else %}
                  0
                {% endif %}
          - action: light.turn_on
            metadata: {}
            target:
              entity_id: !input target_lights
            data:
              brightness: >
                {% set new_brightness = average_brightness - 25 %}
                {% if new_brightness < 25 %}
                  25
                {% else %}
                  {{ new_brightness }}
                {% endif %}
mode: single
