blueprint:
  name: Check If Garden Should Be Watered
  description: Check If Garden Should Be Watered
  domain: automation
  author: Beckynet
  input:
    offset_sunrise:
      name: Offset Relative To Sunrise
      description: Offset Relative To Sunrise
      default: 0
      selector:
        duration:
          enable_millisecond: false
          enable_day: false
    minimal_days_between_watering:
      name: Minimum Number Of Days Between Watering
      description: Minimum Number Of Days Between Watering
      selector:
        number:
          mode: slider
          min: 1
          max: 15
          step: 1
          unit_of_measurement: days
      default: 1
    maximum_watering_time:
      name: Maximum Watering Time
      description: "Maximum Watering Time\nDepending on weather conditions, this maximum watering time will be used between 25% and 100%."
      selector:
        number:
          mode: slider
          min: 20
          max: 120
          step: 20
          unit_of_measurement: minutes
      default: 20
    max_temp_measured:
      name: Maximum Temperature Measured
      description: Helpers Maximum Temperature Measured
      selector:
        entity:
          domain: input_number
          multiple: false
    watering_duration:
      name: Watering Duration
      description: Helpers Watering Duration
      selector:
        entity:
          domain: input_number
          multiple: false

    days_since_last_watering_day:
      name: Days Since Last Watering Days
      description: Sensor Of Days Since Last Watering Day
      selector:
        entity:
          multiple: false
          filter:
            - domain: sensor

    total_rain_fallen_plus_expected:
      name: Total Rain Fallen Plus Expected
      description: Sensor Total Rain Fallen Plus Expected
      selector:
        entity:
          multiple: false
          filter:
            - domain: sensor

    irrigation_script:
      name: Irrigation Script To Call
      description: Name Of The Irrigation Script
      selector:
        entity:
          domain: script
          multiple: false

    irrigation_reset_helpers_script:
      name: Irrigation Reset Helpers Script To Call
      description: Name Of The Irrigation Reset Helpers Script
      selector:
        entity:
          domain: script
          multiple: false

variables:
  offset_sunrise: !input offset_sunrise
  minimal_days_between_watering: !input minimal_days_between_watering
  mdbw_plus_2: "{{ 2 + (minimal_days_between_watering | int) }}"
  mdbw_plus_3: "{{ 3 + (minimal_days_between_watering | int) }}"
  mdbw_plus_4: "{{ 4 + (minimal_days_between_watering | int) }}"
  watering_intense: !input maximum_watering_time
  watering_normal: "{{ (watering_intense * 0.75) | round(0) }}"
  watering_moderate: "{{ (watering_intense * 0.5) | round(0) }}"
  watering_light: "{{ (watering_intense * 0.25) | round(0) }}"
  irrigaton_script: !input irrigation_script
  irrigation_reset_helpers_script: !input irrigation_reset_helpers_script
  max_temp_measured: !input max_temp_measured
  watering_duration: !input watering_duration
  days_since_last_watering_day: !input days_since_last_watering_day
  total_rain_fallen_plus_expected: !input total_rain_fallen_plus_expected

triggers:
- trigger: sun
  event: sunrise 
  offset: !input offset_sunrise

conditions: null

action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: !input max_temp_measured
            above: "36"
          - condition: numeric_state
            entity_id: !input total_rain_fallen_plus_expected
            below: "25.1"
          - condition: numeric_state
            entity_id: !input days_since_last_watering_day
            above: !input minimal_days_between_watering
        sequence:
          - action: input_number.set_value
            data:
              value: "{{ watering_intense }}"
            target:
              entity_id: !input watering_duration
          - action: script.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: !input irrigation_script

      - conditions:
          - condition: template
            value_template: >
              {% set days = states(days_since_last_watering_day) | float %}
              {% set lower = mdbw_plus_2 | float %}
              {% set upper = mdbw_plus_4 | float %}
              {{ lower < days < upper }}
          - condition: numeric_state
            entity_id: !input max_temp_measured
            above: "31"
            below: "36.1"
          - condition: numeric_state
            entity_id: !input total_rain_fallen_plus_expected
            below: "15.1"
        sequence:
          - action: input_number.set_value
            data:
              value: "{{ watering_normal }}"
            target:
              entity_id: !input watering_duration
          - action: script.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: !input irrigation_script
      - conditions:
          - condition: template
            value_template: >
              {% set days = states(days_since_last_watering_day) | float %}
              {% set lower = mdbw_plus_3 | float %}
              {% set upper = mdbw_plus_4 | float %}
              {{ lower < days < upper }}
          - condition: numeric_state
            entity_id: !input max_temp_measured
            above: "26"
            below: "31.1"
          - condition: numeric_state
            entity_id: !input total_rain_fallen_plus_expected
            below: "10.1"
        sequence:
          - action: input_number.set_value
            data:
              value: "{{ watering_moderate }}"
            target:
              entity_id: !input watering_duration
          - action: script.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: !input irrigation_script
      - conditions:
          - condition: template
            value_template: >
              {% set days = states(days_since_last_watering_day) | float %}
              {% set lower = mdbw_plus_3 | float %}
              {% set upper = mdbw_plus_4 | float %}
              {{ lower < days < upper }}
          - condition: numeric_state
            entity_id: !input max_temp_measured
            above: "20"
            below: "26.1"
          - condition: numeric_state
            entity_id: !input total_rain_fallen_plus_expected
            below: "10.1"
        sequence:
          - action: input_number.set_value
            data:
              value: "{{ watering_light }}"
            target:
              entity_id: !input watering_duration
          - action: script.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: !input irrigation_script
      - conditions:
          - condition: template
            value_template: >
              {% set days = states(days_since_last_watering_day) | float %}
              {% set lower = mdbw_plus_3 | float %}
              {% set upper = mdbw_plus_4 | float %}
              {{ lower < days < upper }}
        sequence:
          - action: script.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: !input irrigation_reset_helpers_script
    default: []
