blueprint:
  name: IKEA Rodret Z2M V2
  description: '## Control Light(s) with IKEA RODRET (E2201) Dimmer remote (v2.0)


                  Only for use with Zigbee2MQTT
                  (cf [MQTT](https://www.home-assistant.io/integrations/mqtt) + [Z2M addon](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt#installation))


                  Available controls:

                  - Press the **on** button to turn on the light(s)

                  - Press the **off** button to turn off the light(s)

                  - Press and hold the **on** button to increase the brightness

                  - Press and hold the **off** button to decrease the brightness down to 10%'
  domain: automation
  author: Beckynet
  homeassistant:
    min_version: 2024.10.0
  input:
    z2m_base_topic:
      name: Zigbee2MQTT Base Topic
      description: 'Zigbee2MQTT Base Topic, take a look in your Z2M configuration under Setting / MQTT / Base Topic.
      Note that these values are case sensitive.
      Respect lower and upper case letters
      zigbee2mqtt/rodret/action'
      default: zigbee2mqtt
      selector:
        text:
    target_lights:
      name: Light
      description: Light(s) or Ligth group to control
      selector:
        entity:
          filter:
          - domain:
            - light
          multiple: true

trigger_variables:
  z2m_base_topic: !input z2m_base_topic
  light_entities: !input target_lights

triggers:
  - trigger: mqtt
    topic: !input z2m_base_topic
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == 'on' }}"
        sequence: 
          - action: light.turn_on
            target:
              entity_id: !input target_lights

      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == 'off' }}"
        sequence:
          - action: light.turn_off
            target:
              entity_id: !input target_lights

      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == 'brightness_move_up' }}"
        sequence:
          - variables:
              total_brightness: >
                {% set ns = namespace(total = 0) %}
                {% for light in light_entities %}
                  {% if state_attr(light, 'brightness') is not none %}
                    {% set ns.total = ns.total + state_attr(light, 'brightness') %}
                  {% endif %}
                {% endfor %}
                {{ ns.total }}
              light_count: >
                {% set ns = namespace(count = 0) %}
                {% for light in light_entities %}
                  {% if state_attr(light, 'brightness') is not none %}
                    {% set ns.count = ns.count + 1 %}
                  {% endif %}
                {% endfor %}
                {{ ns.count }}
              average_brightness: >
                {% if light_count > 0 %}
                  {{ (total_brightness / light_count) | int }}
                {% else %}
                  0
                {% endif %}
          - action: light.turn_on
            metadata: {}
            target:
              entity_id: !input target_lights
            data:
              brightness: >
                {% set new_brightness = average_brightness + 50 %}
                {% if new_brightness > 255 %}
                  255
                {% else %}
                  {{ new_brightness }}
                {% endif %}

      - conditions: 
          - condition: template
            value_template: "{{ trigger.payload == 'brightness_move_down' }}"
        sequence:
          - variables:
              total_brightness: >
                {% set ns = namespace(total = 0) %}
                {% for light in light_entities %}
                  {% if state_attr(light, 'brightness') is not none %}
                    {% set ns.total = ns.total + state_attr(light, 'brightness') %}
                  {% endif %}
                {% endfor %}
                {{ ns.total }}
              light_count: >
                {% set ns = namespace(count = 0) %}
                {% for light in light_entities %}
                  {% if state_attr(light, 'brightness') is not none %}
                    {% set ns.count = ns.count + 1 %}
                  {% endif %}
                {% endfor %}
                {{ ns.count }}
              average_brightness: >
                {% if light_count > 0 %}
                  {{ (total_brightness / light_count) | int }}
                {% else %}
                  0
                {% endif %}

          - action: light.turn_on
            metadata: {}
            target:
              entity_id: !input target_lights
            data:
              brightness: >
                {% set new_brightness = average_brightness - 50 %}
                {% if new_brightness < 25 %}
                  25
                {% else %}
                  {{ new_brightness }}
                {% endif %}
mode: single
