blueprint:
    name: Toggle Light(s) On Motion Detection
    description: '## Toggle Light(s) On Motion Detection
	
					choose the ignition time'
    domain: automation
    author: Beckynet
    homeassistant:
      min_version: 2024.8.0
	motion_entity:
	  name: Motion Sensor
	  description: The motion detector that acts as a trigger
	  selector:
		entity:
		  filter:
			domain:
			  - binary_sensor
			device_class: 
			  - occupancy
			  - presence
			  - motion

        wait_time:
          name: Wait Time
          description: Time to leave the light on after no presence is reported
          selector:
            number:
              mode: slider
              min: 0
              max: 720
              step: 15
              unit_of_measurement: seconds
          default: 60

        light_target:
          name: Light
          description: Light(s) or Ligth group to control
          selector:
            entity:
              filter:
                domain:
                  - light
              multiple: true

trigger:
  - platform: state
    entity_id: !input motion_entity
    from: "off"
    to: "on"
    id: "on"
  - platform: state
    entity_id: !input motion_entity
    from: "on"
    to: "off"
    id: "off"
    for:
      hours: 0
      minutes: 0
      seconds: !input wait_time

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - "on"
        sequence:
          - action: light.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: !input light_target
      - conditions:
          - condition: trigger
            id:
              - "off"
        sequence:
          - action: light.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: !input light_target
mode: single
